name: Notify on PR & Comments

on:
  pull_request:
    types: [opened, closed]

  issue_comment:
    types: [created]

jobs:
  notify-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Export PR description to env (supports multiline safely)
        run: |
          echo "PR_DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify Flock about PR
        run: |
          echo "Raw PR_DESCRIPTION:"
          echo "$PR_DESCRIPTION"

          # Escape PR description using jq to safely insert into JSON payload
          ESCAPED_DESC=$(echo "$PR_DESCRIPTION" | jq -Rs .)

          curl -X POST -H "Content-Type: application/json" \
            -d "{
              \"text\": \"🔔 *Pull Request ${{ github.event.action }}*\n\n*Title:* ${{ github.event.pull_request.title }}\n\n*Description:* $ESCAPED_DESC\n\n*Author:* ${{ github.event.pull_request.user.login }}\n\n*From:* \`${{ github.event.pull_request.head.ref }}\` ➡️ *To:* \`${{ github.event.pull_request.base.ref }}\`\n\n🔗 *PR Link:* ${{ github.event.pull_request.html_url }}\"
            }" \
            https://api.flock.com/hooks/sendMessage/61adf044-a5e9-4c93-97bb-3112736b4bcf

  notify-comment:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Export PR comment to env (supports multiline safely)
        run: |
          echo "COMMENT_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.comment.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify Flock about PR Comment
        run: |
          echo "Raw COMMENT_BODY:"
          echo "$COMMENT_BODY"

          # Escape comment body using jq to safely insert into JSON payload
          ESCAPED_COMMENT=$(echo "$COMMENT_BODY" | jq -Rs .)

          curl -X POST -H "Content-Type: application/json" \
            -d "{
              \"text\": \"💬 *New comment on PR*\n\n*Commenter:* ${{ github.event.comment.user.login }}\n\n*Comment:* $ESCAPED_COMMENT\n\n🔗 *PR Link:* ${{ github.event.issue.html_url }}\"
            }" \
            https://api.flock.com/hooks/sendMessage/61adf044-a5e9-4c93-97bb-3112736b4bcf
